blueprint: page

title: Batiment

status:
  draft: Brouillon
  listed: Public

num: zero

image:
  back: black
  query: page.coverImage.toFile()
  icon: 📝


columns:

  - width: 1/1
    fields:
      pageTitle:
        label: Liste des Labs
        type: headline

  - width: 1/3
    fields:
      coverImage:
        label: Image de couverture
        info: Utilisiée seulement pour l'administration
        type: files
        query: page.images
        multiple: false
        required: false

  - width: 3/4
    sections:
      drafts:
        label: Brouillon
        type: pages
        status: draft
        templates: batiment.lab
  - width: 3/4
    sections:
      published:
        label: Public
        type: pages
        status: listed
        templates: batiment.lab
