blueprint: page

title: Article
num: '{{ page.publicationDate.toDate("Ymd") }}'
icon: 📖

status:
  draft:
    label: Draft
    text: L'article est encore en mode brouillon. Il ne peut être vu que par les éditeurs ayant accès au panneau.
  unlisted:
    label: In Review
    text: L'article est en ligne et peut être visité avec l'URL directe. L'équipe doit encore donner le feu vert pour le publier.
  listed:
    label: Published
    text: L'article est en ligne et répertorié dans la section "News"

columns:
  cover:
    width: 2/3
    fields:
      coverImage:
        label: Image de couverture
        type: files
        query: page.images
        multiple: false
        required: true
      textIntro:
        required: true
        label: Text d'introduction
        type: writer
        nodes: false
        marks:
          - italic
          - link
          - email
          - underline

  tags:
    width: 1/3
    fields:
      typeOfContent:
        type: select
        required: true
        options:
          event:    Événement
          article:  Article
          project:  Projet
          construction: Le chantier
      eventDate:
        type: date
        label: Date de l'événement
        time: false
        default: now
        required: true
        when:
          typeOfContent: event
      publicationDate:
        type: date
        label: Date de publication
        time: false
        default: now
        required: true
      author:
        label: Auteur.trice
        type: users
        multiple: false


  main:
    width: 2/3
    fields:
      blockContent:
        label: Contenu
        type: blocks
        fieldsets:
          - heading
          - text
          - image
          - quote

#  gallery:
#    width: 2/3
#    fields:
#      galleryImage:
#        label: Galerie d'images (autre fichier comme des PDF?)
#        help: On pourrait ajouter une galerie de "embed" YouTube/Vimeo
#        type: files
#        query: page.images
#        multiple: true
