blueprint: page

title: La Fondation

image:
  back: black
  query: page.coverImage.toFile()
  icon: 📝

options:
  changeSlug: false
  delete: false
  changeTemplate: false
  changeStatus: false
  duplicate: false
  sort: false


columns:

  - width: 1/3
    fields:
      coverImage:
        label: Image de couverture
        info: Utilisiée seulement pour l'administration
        type: files
        query: page.images
        multiple: false
        required: false

  - width: 3/4
    fields:
      textIntro:
        required: true
        label: Text d'introduction
        type: writer
        nodes: false
        marks:
          - italic
          - link
          - email
          - underline
      blockContent:
        label: Contenu
        type: blocks
        fieldsets:
          - heading
          - text
          - image
          - quote
      team:
        type: structure
        label: L'équipe
        extends: fields/teamMember
        sortBy: name
      conseil:
        type: structure
        label: Conseil de Fondation
        extends: fields/teamMember
        sortBy: name
