blueprint: page

title: Les partenaires

image:
  back: black
  query: page.coverImage.toFile()
  icon: 📝

options:
  changeSlug: false
  delete: false
  changeTemplate: false
  changeStatus: false
  duplicate: false
  sort: false


columns:

  - width: 1/1
    fields:
      pageTitle:
        label: Liste des Labs
        type: headline

  - width: 1/3
    fields:
      coverImage:
        label: Image de couverture
        type: files
        query: page.images
        multiple: false
        required: true

#status:
#  draft: Brouillon
#  listed: Public
  - width: 2/3
    fields:
      textIntro:
        required: true
        label: Text d'introduction
        type: writer
        nodes: false
        marks:
          - italic
          - link
          - email
          - underline
      partners:
        type: structure
        label: Partenaires
        extends: fields/teamMember
        sortBy: name
