blueprint: page

preview: text
wysiwyg: true
icon: text
fields:
  text:
    type: writer
    placeholder: field.blocks.text.placeholder
    nodes:
      - bulletList
      - paragraph
#      - heading
    marks:
      - italic
      - bold
      - link
      - email
      - underline
