sections:
  draft:
    label: Non-publié.s
    type: pages
    status: draft
    layout: cards
    size: tiny
    image: false
    template:
      - contact
      - evolution
      - fondation
      - introduction
      - plan
  sections:
    label: Publié.s
    type: pages
    status: listed
    layout: cards
    size: huge
    image: false
