sections:
  draft:
    label: non-publié.s
    type: pages
    status: draft
    layout: cards
    size: medium
    image: false
    template:
      - contact
      - evolution
      - fondation
      - introduction
      - plan
  sections:
    label: publié.s
    type: pages
    status: listed
    layout: cards
    size: medium
    image: false
