options:
  changeTitle: false


columns:
  - width: 1/3
    sections:
      site_description:
        headline: Informations générales
        type: pages
        image:
          cover: true
        status: listed
        template:
          - home-site_description
        layout: cards
        size: medium
        text: ""

  - width: 1/3
    sections:
      batiment:
        headline: Le bâtiment
        type: pages
        image:
          cover: true
        status: listed
        template:
          - home-batiment
        layout: cards
        size: medium
        text: ""


  - width: 1/3
    sections:
      foundation:
        headline: Fondation ForPro
        type: pages
        image:
          cover: true
        status: listed
        template:
          - home-foundation
        layout: cards
        size: medium
        text: ""



  - width: 1/3
    sections:
      partners:
        headline: Les partenaires
        type: pages
        image:
          cover: true
        status: listed
        template:
          - home-partenaires
        layout: cards
        size: medium
        text: ""

  - width: 1/3
    sections:
      articles:
        headline: Blog
        type: pages
        image:
          cover: true
        status: listed
        template:
          - home-blog
        layout: cards
        size: medium
        text: ""
