sections:
  draft:
    label: brouillons
    type: pages
    status: draft
    layout: cards
    size: medium
    image: false
    template:
      - contact
      - evolution
      - fondation
      - introduction
      - plan
#  unlisted:
#    label: sections non listées
#    type: pages
#    status: unlisted
#    layout: cards
#    size: medium
#    image: false
  sections:
    type: pages
    status: listed
    layout: cards
    size: medium
    image: false
