blueprint: site

title: ForPro

options:
  changeTitle: false

columns:
  - width: 1/3
    sections:
      site_description:
        headline: Home
        type: pages
        image:
          cover: true
        status: listed
        template:
          - home
        layout: cards
        size: medium
        text: ""

  - width: 1/3
    sections:
      batiment:
        headline: Le bâtiment
        type: pages
        image:
          cover: true
        status: listed
        template:
          - batiment
        layout: cards
        size: medium
        text: ""


  - width: 1/3
    sections:
      foundation:
        headline: Fondation ForPro
        type: pages
        image:
          cover: true
        status: listed
        template:
          - home-foundation
        layout: cards
        size: medium
        text: ""



  - width: 1/3
    sections:
      partners:
        headline: Les partenaires
        type: pages
        image:
          cover: true
        status: all
        template:
          - partenaires
        layout: cards
        size: medium
        text: ""

  - width: 1/3
    sections:
      articles:
        headline: News
        type: pages
        image:
          cover: true
        status: listed
        template:
          - blog
        layout: cards
        size: medium
        text: ""
