options:
  changeTitle: false


columns:
  introTitle:
    width: 1/1
    fields:
      introTitleSettings:
        label: Introduction
        type: headline

  intro:
    width: 1/1
    fields:
      introText:
        label: Texte d'introduction
        type: writer
        nodes:
          - heading: false
          - paragraph: true
          - bulletList: false
          - orderedList: false
        marks:
          - bold
          - italic

  sectionTitle:
    width: 1/1
    fields:
      sectionTitleSettings:
        label: Sections du site
        type: headline

  top:
    width: 1/1
    sections:
      draft:
        label: Non-publié.s
        type: pages
        status: draft
        layout: cards
        size: tiny
        image: false
        template:
          - team
          - evolution
          - foundation
          - introduction
          - plan
      sections:
        label: Publié.s
        type: pages
        status: listed
        layout: cards
        size: huge
        image: false


  footerTitle:
    width: 1/1
    fields:
      footerTitleSettings:
        label: Bas de page du site
        type: headline

  left:
    width: 1/2
    sections:
      footerLeft:
        type: fields
        fields:
          textLeft:
            label: gauche
            type: writer
            marks:
              - bold
              - link
              - email
            nodes: false

  right:
    width: 1/2
    fields:
      textRight:
        label: droite
        type: writer
        marks:
          - bold
          - link
          - email
        nodes: false

  newsletter:
    width: 1/1
    fields:
      newsletterCode:
        label: Code d'Infomaniak pour le formulaire d'inscription à la newsletter
        type: writer
        marks: false
        nodes: false
        inline: true
